language: python

python:
  - 3.6

sudo: false

before_install:
  - export PYTHONPATH=$HOME/build/farwydi/vigilant-pancake/src

install:
  - pip install -r requirements.tests.txt

script:
  - pytest --cov=./src tests

after_script:
  - coverage xml
  - python-codacy-coverage -r coverage.xml

notifications:
  email:
    on_success: never
    on_failure: always