language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=vigilant-pancake tests

after_script:
  - coverage xml
  - python-codacy-coverage -r coverage.xml