PLANCK_LENGTH = 12
COUNT_LINE_OBJECT = 60
GRID_SIZE = (COUNT_LINE_OBJECT, COUNT_LINE_OBJECT)
HEADER_SIZE = 100
DISPLAY_SIZE = (COUNT_LINE_OBJECT * PLANCK_LENGTH, COUNT_LINE_OBJECT * PLANCK_LENGTH + HEADER_SIZE)
