"""
Configuration
"""
WORLD_SIZE = (920, 920)
WORLD_NAME = 'gen test'
WORLD_START_FOOD_COUNT = 5
WORLD_START_POISON_COUNT = 20
ROUND_COUNT = -1
REAL_MODE = True
PLAYER_VISION = 30
PLAYER_COST_STEP = 2
BOX_SIZE = 15
PLAYER_STEP = 10
PLAYER_COUNT = 11
PLAYER_SIZE = 5
PLAYER_MAX_HEALTH = 2000
SCORE = 10
DELAY = 1
